% Given the trial conditions and prompts, get the expected correct response
% for each trial in advance (to compare with actual button presses later)

function correctResponses = getCorrectResponses_pilot(taskStruct)
dbstop if error
%% Getting unique characteristics of each stimulus
stims = {'..\stimuli\Task_Stim_Version2\Animals\Pair1\1.jpg', {'Colorful','Single'}; ...
    '..\stimuli\Task_Stim_Version2\Animals\Pair1\4.jpg', {'notColorful','Multiple'}; ...
    '..\stimuli\Task_Stim_Version2\Animals\Pair5\191s.jpg', {'Colorful','Multiple'}; ...
    '..\stimuli\Task_Stim_Version2\Animals\Pair1\202.jpg', {'Colorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair5\207.jpg', {'notColorful','Single'}; ...
    '..\stimuli\Task_Stim_Version2\Animals\Pair2\2.jpg', {'Colorful','Multiple'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair2\205.jpg', {'notColorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair3\133s.jpg', {'Colorful','Multiple'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair3\204.jpg', {'notColorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair4\16s 2.jpg', {'notColorful','Multiple'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair4\181s.jpg', {'Colorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair5\209.jpg', {'Colorful','Multiple'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair5\210.jpg', {'notColorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair6\203.jpg', {'Colorful','Single'};...
    '..\stimuli\Task_Stim_Version2\Animals\Pair6\42s.jpg', {'notColorful','Multiple'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair1\24s.jpg', {'notColorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair2\13s 2.jpg', {'Colorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair4\15s.jpg', {'Colorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair5\38s.jpg', {'Colorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair1\8s 3.jpg', {'Colorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair2\304.jpg', {'Colorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair2\7s.jpg', {'notColorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair3\17s 3.jpg', {'Colorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair3\4s.jpg', {'notColorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair4\0s 2.jpg', {'notColorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair4\308.jpg', {'Colorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair5\11s.jpg', {'notColorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair5\310.jpg', {'Colorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair6\28s.jpg', {'notColorful','New'};...
    '..\stimuli\Task_Stim_Version2\Cars\Pair6\48s.jpg', {'Colorful','Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair1\1s.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair1\2s.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair2\305.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair2\307.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair3\306.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair3\308.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair4\3s 2.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair4\3s.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair5\21s.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair5\4s.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair6\43s.jpg', {'Old'};...
    '..\stimuli\Task_Stim_Version2\Faces\Pair6\46s.jpg', {'New'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair1\2s 2.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair1\2s.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair6\407.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair1\402.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair2\42s.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair2\7s.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair3\401.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair3\403.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair4\404.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair4\405.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair5\406.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair5\408.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair6\402.jpg', {'Multiple'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair6\411.jpg', {'Single'};...
    '..\stimuli\Task_Stim_Version2\Fruits\Pair6\411.jpg', {'Single'};...
    };


correctResponses = nan(taskStruct.nTrials,1);
trialVariant = taskStruct.antiTask+taskStruct.promptVariant;
for tI = 1:taskStruct.nTrials
    axis = taskStruct.trialAxis(tI);
    category = taskStruct.trialCategories(tI);
    trialAxis = taskStruct.categoryAndAxis{2,category}{axis};
    switch trialAxis
        case 'Colorful'
            targetFeature = 'notColorful';
            if trialVariant(tI)==1
                targetFeature = 'Colorful';
            end
        case 'Count'
            targetFeature = 'Single';
            if trialVariant(tI)==1
                targetFeature = 'Multiple';
            end
        case 'Identical'
            targetFeature = '';
        case 'New'
            targetFeature = 'Old';
            if trialVariant(tI)==1
                targetFeature = 'New';
            end
    end

    trialText = {taskStruct.leftText{tI}, taskStruct.rightText{tI}};
    if strcmp(trialAxis,'Identical') 
        if strcmp(taskStruct.trialStims{tI, 1},taskStruct.trialStims{tI, 2}) % Correct response = yes (in task)/ no (antitask)                
            if ~taskStruct.antiTask(tI)
                correctKey = find(contains(trialText,'Yes'));
            else
                correctKey = find(contains(trialText,'No'));
            end

        else % Correct response = no (in task) / yes (anti task)
            if ~taskStruct.antiTask(tI)
                correctKey = find(contains(trialText,'No'));
            else
                correctKey = find(contains(trialText,'Yes'));
            end                
        end                 
    else % Other conditions than identical
        stim1Idx = find(contains(stims(:,1),taskStruct.trialStims{tI,1} ));
        stim2Idx = find(contains(stims(:,1),taskStruct.trialStims{tI,2} ));
        stimFeatures = {stims{stim1Idx,2},stims{stim2Idx,2}};             %#ok<FNDSB>
        stimWithTargetFeature = any(strcmp(stimFeatures{2},targetFeature ))+1;          
        if stimWithTargetFeature == 1
            correctKey = find(contains(trialText,'First'));
        else
            correctKey = find(contains(trialText,'Second'));
        end                    
    end
    correctResponses(tI) = correctKey;
end



end